### ISSUE TITLE
How to ? Update(PUT) a field with default_factory=datetime.now ? 

### ISSUE THREAD

**Issue by JulienGioux** [volfpeter/motorhead#6]
Hi,

Maybe someone could help...
I want to update a field "last_update" with "datetime.now" each time a PUT request is validate, and to store this key as Date type in mongodb

The only solution I've found is to add the key:value directly in the dict in my "_convert_for_update" function... But i'm not really satisfied with this solution. Maybe there is a better and proper way to do that ?

Here is my basic UserUpdate class:

```
class UserUpdate(BaseDocument):
    """
    User update model
    """
    name: str | None = None
    surname: str | None = None
    email: EmailStr | None = None
    nickname: str | None = None
    last_update: UTCDatetime = Field(default_factory=datetime.now)
```
and here my "_convert_for_update" function:
```
    async def _convert_for_update(self, data: UserUpdate) -> UpdateObject:
        result_dict = {**(await super()._convert_for_update(data))}
        result_dict['$set'].update({'last_update': data.last_update})
        return result_dict
```

**Comment by volfpeter** [comment]
Hi,

Thanks for giving the project a go!

I assume you use `UserUpdate` on the API as the payload type. In that case my first comment is that you shouldn't expose `last_update` there, because a client might actually decide to send this data and make your database invalid. I recommend an update model like this:

```python
class UserUpdate(BaseDocument):
    """
    User update model.
    """
    name: str | None = None
    surname: str | None = None
    email: EmailStr | None = None
    nickname: str | None = None
```

Then you could implement `_convert_for_update()` like this:

```python
    async def _convert_for_update(self, data: UserUpdate) -> UpdateObject:
        return {"$set": {**self._mongo_dump(data), "last_update": datetime.now(tz=timezone.utc)}}
```

No need to call `super()._convert_for_update()` as that's just a default implementation.

-----

An alternative solution -- that maybe behaves better with static type checkers for example -- is to declare two update models, one without `last_update` (exposed on the API), and one with it (for backend use only), like this:

```python
class AIPUserUpdate(BaseDocument):
    """
    User update model.
    """
    name: str | None = None
    surname: str | None = None
    email: EmailStr | None = None
    nickname: str | None = None

class UserUpdate(APIUserUpdate):
    last_update: UTCDatetime  # Important, no default here

    @classmethod
    def from_api_update(cls, data: APIUserUpdate) -> UserUpdate:  # requires from __future__ import annotations, or even better the Self type if you're on Python 3.11.
        return cls(**data.dict(), last_update=datetime.now(tz=timezone.utc))
```

Then you could either do the `AIPUserUpdate` to `UserUpdate` conversion outside the service, or inside the `_convert_for_update()` method like this:

```python
async def _convert_for_update(self, data: APIUserUpdate) -> UpdateObject:
        return await super()._convert_for_update(UserUpdate.from_api_update(data))
```

------

If none of these options are sufficiently good, maybe it'd make sense to add an extra hook method to `Service` that returns a Pydantic model instance containing extra data that must be set in every update. (Actually, two methods, one for insert and one for update).

Let me know what you think.

**Comment by JulienGioux** [comment]
thanks a lot !!
As you can see i'm kind of noobs in python... 
You're first example make me realise that i was stuck with the default implementation and the second one is exactly what i'm trying to do...

Hope your work will be used by many people, it's great ;)

**Comment by volfpeter** [comment]
I admit I didn't have time to actually try the code from my comment, I mostly focused on the structure.
Could you maybe check the value `UserUpdate.from_api_update()` and the return value of `await super()._convert_for_update(UserUpdate.from_api_update(data))`? Do they seem correct?

I'll add a working example for this use-case to the docs when I have some time.

**Comment by JulienGioux** [comment]
I understand and I am already very grateful for your interest in my concerns.

UserUpdate.from_api_update() :
`name='string' surname='string' email='user@example.com' nickname='string' last_update=datetime.datetime(2023, 9, 13, 13, 57, 52, 313418, tzinfo=datetime.timezone.utc)`

await super()._convert_for_update(UserUpdate.from_api_update(data)) :
`{'$set': {'name': 'string', 'surname': 'string', 'email': 'user@example.com', 'nickname': 'string', 'last_update': '2023-09-13T13:57:52.313418Z'}}`

I don't want to say something stupid but to have a time Date in mongodb i think the result of `await super()._convert_for_update(UserUpdate.from_api_update(data))` should be:

`
{'$set': {'name': 'string', 'surname': 'string', 'email': 'user@example.com', 'nickname': 'string', 'last_update': datetime.datetime(2023, 9, 13, 14, 19, 38, 969798, tzinfo=datetime.timezone.utc)}}
`

In fact, this is exactly the problem that I have been trying to get around from the start... There is probably a solution with a serializer, but no matter how much I look at the fastAPI, pydantic and motorhead documentation, I don't see how to do...

PS: And sorry for my poor English ! lol

**Comment by volfpeter** [comment]
You're right! Actually, I think I need to fix `Service._mongo_dump()`... This just turned into a nice bug report. I'll do my best to fix this soon, then the code from my previous comment should work.

**Comment by volfpeter** [comment]
If you feel like giving the fix a try, feel free to submit a PR.

I think the bug is at line 814, where `data.model_dump()` gets `mode="json"` instead of `mode="python"`.

**Comment by JulienGioux** [comment]
ok, i need to go for now, but i'll try as soon as possible...

**Comment by volfpeter** [comment]
Fixed and published a new version of the package to PyPI (0.2309.0). Please update the package and try the code from my previous comment, it should be fine. I'll update the docs soon.

**Comment by JulienGioux** [comment]
Arf too late !! 
It's working, thanks a lot...

**Comment by volfpeter** [comment]
You're welcome. And thanks for the bug report!

**Comment by volfpeter** [comment]
One last note:

Instead of `return cls(**data.dict(), last_update=datetime.now(tz=timezone.utc))`, you should write `return cls(**data.model_dump(), last_update=datetime.now(tz=timezone.utc))`, because `BaseModel.dict()` is deprecated. :slightly_smiling_face:

**Comment by JulienGioux** [comment]
j'avais déjà corrigé, but thanks ;)

**Comment by JulienGioux** [comment]
There is another issue. If a field in UserUpdate is not set or None fastApi raise an error and ask for a valid value...

```
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'string_type', 'loc': ('response', 'nickname'), 'msg': 'Input should be a valid string', 'input': None, 'url': 'https://errors.pydantic.dev/2.3/v/string_type'}
```

...still investigating

**Comment by volfpeter** [comment]
Based on the exception, `nickname` is `None` in the DB, but your response model expects a `str`.

**Comment by JulienGioux** [comment]
You're right but the value is converted to null in db automatically with the same error even with a str in db...

**Comment by volfpeter** [comment]
Could you maybe paste your code here?

**Comment by volfpeter** [comment]
Idea: in `_convert_for_update()` you should probably use `data.model_dump(exclude_unset=True)`.

**Comment by JulienGioux** [comment]
this is what i'have done, my message was edited...

For a complete example of this special case, if you want to include this in your documentation, i've made some change to easily add a field `last_update date` in any Update* class ...

-  model.py

```python

class UpdateLastUTCDatetime(BaseDocument):
    """
    User Last update  model
    """
    last_update_date: UTCDatetime = Field(default_factory=datetime.now)


class UserUpdate(UpdateLastUTCDatetime):
    """
    User update model
    """
    name: str | None = None
    surname: str | None = None
    email: EmailStr | None = None
    nickname: str | None = None

    @classmethod
    def add_user_update_date(cls, data: UpdateLastUTCDatetime) -> Self:
        return cls(**data.model_dump(exclude_none=True, exclude_defaults=False, mode="python"))

```

-  service.py

```python

    async def _convert_for_update(self, data: UpdateLastUTCDatetime) -> UpdateObject | Sequence[UpdateObject]:
        return await super()._convert_for_update(UserUpdate.add_user_update_date(data))

```

**Comment by volfpeter** [comment]
I think `exclude_none=True` is incorrect (what if `None` is a valid value for a model property). `mode="python"` is the default, `exclude_defaults=False` is also the default. See my comment above, I think you must set `exclude_unset=True` (same as in the `_mongo_dump()`).

**Comment by JulienGioux** [comment]
In this specific case `exclude_unset=True` does not work because pydantic default or factory_default are considered _unset...

**Comment by volfpeter** [comment]
With the example in my previous [comment](https://github.com/volfpeter/motorhead/issues/6#issuecomment-1717458777) it should work, I didn't add a default (and added a comment) to `last_update` exatly for this reason.

**Comment by JulienGioux** [comment]
OK, my example works with `exclude_unset=True` but i need a default value
[Last comment](https://github.com/volfpeter/motorhead/issues/6#issuecomment-1718369131) edited.

**Comment by JulienGioux** [comment]
I'm stupid.... Pydantic v2 can do what i want easily !

No need a parent or child class, no need "_convert_for_update()"....

Now we have the @computed_field and the @property decorator !!!

```python
class UserUpdate(BaseDocument):
    """
    User update model
    """
    name: str | None = None
    surname: str | None = None
    email: EmailStr | None = None
    nickname: str | None = None

    @computed_field
    @property
    def last_update_date(self) -> UTCDatetime:
        return datetime.now(timezone.utc)
```

Now, last_update_date is not exposed... and that's all i need ^^
